### ISSUE TITLE
Add support for globs in `jstest` runner

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/dance#289]
```yaml
runner: jstest
args:
  - tests/mongo/jstests/core/basic1.js
  - tests/mongo/jstests/core/basic2.js
```

It should be possible to replace that configuration with:
```yaml
runner: jstest
args:
  - tests/mongo/jstests/core/basic*.js
```

There is no shell, so we should do that in Go, using https://pkg.go.dev/path/filepath#Glob and similar functions.
