### ISSUE TITLE
Integrate FerretDB testing with SQLite

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/dance#463]
Let's start by thinking (or completely rethinking) the YAML structure. Could we use YAML anchors or something? or just some common section?

**Comment by b1ron** [comment]
I think the simplest approach would be to treat different backends as different databases.

```yml
results:
  # new service
  ferretdb-postgres:
    stats:
      expected_fail: 1
    fail:
      - mongo/jstests/core/query/basic1.js
  # another new service
  ferretdb-sqlite:
    stats:
      expected_fail: 1
    fail:
      - mongo/jstests/core/query/basic1.js

  mongodb:
    stats:
      expected_pass: 8

```
